### ISSUE TITLE
Refreshing animation is frozen

### ISSUE THREAD

**Issue by mauriciogior** [dinuscxj/RecyclerRefreshLayout#6]
The refreshing animation is always static. 
Here is an example:

<img width="230" alt="screen shot 2016-08-25 at 6 35 57 pm" src="https://cloud.githubusercontent.com/assets/2918286/17986777/d268ac96-6af2-11e6-87b0-3acc35f5ab7a.png">

--

Ps: only happens on emulator.

**Comment by dinuscxj** [comment]
Maybe your emulator not support AnimationDrawable well, the default animation just defined in the xml [spinner](https://github.com/dinuscxj/RecyclerRefreshLayout/blob/master/recyclerrefreshlayout/src/main/res/drawable/spinner.xml)

**Comment by dinuscxj** [comment]
@mauriciogior the compileSdkVersion that you are using is lower 23 ?

**Comment by mauriciogior** [comment]
@dinuscxj I'm using 24.

**Comment by dinuscxj** [comment]
@mauriciogior 👌！

**Comment by dinuscxj** [comment]
I get it.  the line 65 ~ 66  of the [RefreshView](https://github.com/dinuscxj/RecyclerRefreshLayout/blob/master/recyclerrefreshlayout/src/main/java/com/dinuscxj/refresh/RefreshView.java) need to reverse the order. The refreshing animation is always static, because the AnimationDrawable is not yet fully attached to the window.  if you want to learn more, you can click the [link](https://developer.android.com/guide/topics/graphics/drawable-animation.html)
